[metadata]
name = toronto-bikeshare
version = 0.0.1
license_file = LICENSE
long_description = file:README.md
url = https://github.com/constcorrectness/

[options]
package_dir =
  = src

packages = find:

[options.packages.find]
where = src


exclude = test*

